Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	SingleCellReadSimulator
	6	indexMutations
	6	insertMutations
	6	simulateReads
	6	sortMutations
	6	zipMutations
	31

[Wed May 15 19:37:05 2019]
rule sortMutations:
    input: Data/Mutations/Mutations3_5.vcf
    output: Data/Mutations/sortedMutations3_5.vcf
    jobid: 30
    wildcards: treename=3, sample=5

[Wed May 15 19:37:05 2019]
Finished job 30.
1 of 31 steps (3%) done

[Wed May 15 19:37:05 2019]
rule zipMutations:
    input: Data/Mutations/sortedMutations3_5.vcf
    output: Data/Mutations/sortedMutations3_5.vcf.gz
    jobid: 23
    wildcards: treename=3, sample=5

Removing temporary output file Data/Mutations/sortedMutations3_5.vcf.
[Wed May 15 19:37:05 2019]
Finished job 23.
2 of 31 steps (6%) done

[Wed May 15 19:37:05 2019]
rule indexMutations:
    input: Data/Mutations/sortedMutations3_5.vcf.gz
    output: Data/Mutations/sortedMutations3_5.vcf.gz.tbi
    jobid: 24
    wildcards: treename=3, sample=5

[Wed May 15 19:37:05 2019]
Finished job 24.
3 of 31 steps (10%) done

[Wed May 15 19:37:05 2019]
rule insertMutations:
    input: Data/Mutations/sortedMutations3_5.vcf.gz, Data/Mutations/sortedMutations3_5.vcf.gz.tbi
    output: Data/Mutations/InsertedMutations3_5.fa
    jobid: 12
    wildcards: treename=3, sample=5

[Wed May 15 19:37:05 2019]
Error in rule insertMutations:
    jobid: 12
    output: Data/Mutations/InsertedMutations3_5.fa

RuleException:
CalledProcessError in line 99 of /Users/leonorschubert/Desktop/Aramis/ETH/Bachelor Thesis/Code/Snakefile:
Command 'set -euo pipefail;  cat Test/ReferenceGenome.fa | bcftools consensus Data/Mutations/sortedMutations3_5.vcf.gz.tbi > Data/Mutations/InsertedMutations3_5.fa' returned non-zero exit status 255.
  File "/Users/leonorschubert/Desktop/Aramis/ETH/Bachelor Thesis/Code/Snakefile", line 99, in __rule_insertMutations
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Removing output files of failed job insertMutations since they might be corrupted:
Data/Mutations/InsertedMutations3_5.fa
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/leonorschubert/Desktop/Aramis/ETH/Bachelor Thesis/Code/.snakemake/log/2019-05-15T193705.149581.snakemake.log
